description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 8.6.2
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - run: pnpm install
      shell: bash
  using: composite
