jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run format

name: Format

on:
  pull_request: ~
  push:
    branches:
      - main
