jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run build
      - run: pnpm run lint:eslint-docs

name: Lint ESLint Docs

on:
  pull_request: ~
  push:
    branches:
      - main
