jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run lint:eslint-docs

name: Lint ESLint Docs

on:
  pull_request: ~
  push:
    branches:
      # TODO: change to main when eslint-doc-generator will support ESM
      # @see https://github.com/bmish/eslint-doc-generator/issues/504
      - docs
