jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run test
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: "pnpm changeset:version"
          publish: "pnpm changeset:publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
name: Release

on:
  pull_request: ~
  push:
    branches:
      - main
